// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgCu0F5KmKck9f5wxTiYFkMZePvsPLQw',
    appId: '1:245990157157:web:2cd7c2d03a1466c5b40f8c',
    messagingSenderId: '245990157157',
    projectId: 'cpc357-project-448301',
    authDomain: 'cpc357-project-448301.firebaseapp.com',
    storageBucket: 'cpc357-project-448301.firebasestorage.app',
    measurementId: 'G-GBKKT7WL8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFm3pO94pGnjRsRxbjykgUJlcltaZDFo',
    appId: '1:245990157157:android:b76d2fb8743a3e37b40f8c',
    messagingSenderId: '245990157157',
    projectId: 'cpc357-project-448301',
    storageBucket: 'cpc357-project-448301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4ZhprogEPX_fn4O6uZsHrn4rZrOrUSY',
    appId: '1:245990157157:ios:1a8a1a0b7a27a210b40f8c',
    messagingSenderId: '245990157157',
    projectId: 'cpc357-project-448301',
    storageBucket: 'cpc357-project-448301.firebasestorage.app',
    iosBundleId: 'com.example.smartirrgation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4ZhprogEPX_fn4O6uZsHrn4rZrOrUSY',
    appId: '1:245990157157:ios:1a8a1a0b7a27a210b40f8c',
    messagingSenderId: '245990157157',
    projectId: 'cpc357-project-448301',
    storageBucket: 'cpc357-project-448301.firebasestorage.app',
    iosBundleId: 'com.example.smartirrgation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAgCu0F5KmKck9f5wxTiYFkMZePvsPLQw',
    appId: '1:245990157157:web:eb1629e7604a16a2b40f8c',
    messagingSenderId: '245990157157',
    projectId: 'cpc357-project-448301',
    authDomain: 'cpc357-project-448301.firebaseapp.com',
    storageBucket: 'cpc357-project-448301.firebasestorage.app',
    measurementId: 'G-51HHZ9QJNP',
  );
}
